language: scala

scala:
  - 2.10.7
  - 2.11.12
jdk:
  - oraclejdk7
env: RUN_MIMA=false
matrix:
  include:
  - scala: 2.12.4
    jdk: oraclejdk8
    env: RUN_MIMA=true
  - scala: 2.13.0-M2
    jdk: oraclejdk8

script:
  - sbt clean coverage test coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION "test"
  - if [ "$RUN_MIMA" == "true" ]; then sbt ++$TRAVIS_SCALA_VERSION "+scalaJsonJVM/mimaReportBinaryIssues" ; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
