dist: xenial
group: stable
language: scala

scala:
  - 2.10.7
  - 2.11.12
  - 2.13.0

env:
  - ADOPTOPENJDK=8

matrix:
  include:
  - env: ADOPTOPENJDK=11
    scala: 2.12.8
  - env: ADOPTOPENJDK=8
    scala: 2.12.8
    script:
      - sbt clean coverage test coverageReport
      - sbt ++$TRAVIS_SCALA_VERSION "test"
      - sbt ++$TRAVIS_SCALA_VERSION "+scalaJsonJVM/mimaReportBinaryIssues"

before_install:
  # adding $HOME/.sdkman to cache would create an empty directory, which interferes with the initial installation
  - "[[ -d $HOME/.sdkman/bin/ ]] || rm -rf $HOME/.sdkman/"
  - curl -sL https://get.sdkman.io | bash
  - echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
  - source "$HOME/.sdkman/bin/sdkman-init.sh"

install:
  - sdk install java $(sdk list java | grep -o "$ADOPTOPENJDK\.[0-9\.]*hs-adpt" | head -1)
  - unset JAVA_HOME
  - java -Xmx32m -version

script:
  - sbt ++$TRAVIS_SCALA_VERSION "test"

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.sdkman
