language: scala

scala:
  - 2.10.6
  - 2.11.11
jdk:
  - oraclejdk7
env: RUN_MIMA=false
matrix:
  include:
  - scala: 2.12.2
    jdk: oraclejdk8
    env: RUN_MIMA=true

script:
  - sbt clean coverage test coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION "test"
  - sbt benchmarkJVM/test:compile
  - sbt benchmarkJS/test:compile
#  - if [ "$RUN_MIMA" == "true" ]; then sbt ++$TRAVIS_SCALA_VERSION "+scalaJsonJVM/mimaReportBinaryIssues" ; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
